server:
  port: 8080

spring:
  application:
    name: tracker-server
  main:
    allow-bean-definition-overriding: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:4b
  data:
    redis:
      host: nas.hery.club
      port: 6379
      database: 0
      password: redis


# 配置接口文档
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  # SpringDoc 配置属性
  configs:
    title: Code Tracker API文档
    description: 代码记录接口文档
    version: 1.0.0
    author: Hery
    url: https://github.com/code-tracker
    email: admin@code-tracker.com
    license: Apache License 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0
knife4j:
  enable: true
logging:
  level:
    org.dromara.trans.listener.TransMessageListener: error

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: sa-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# Minio 配置

minio:
  endpoint: http://nas.hery.club:9000
  bucketName: code-tracker
  access-key: minio
  secret-key: minio
